### ISSUE TITLE
fuzzy matching

### ISSUE THREAD

**Issue by nicolasbalao** [nicolasbalao/cli_project_manager#12]
## Description
We want to implement a fuzzy matching algorithm in our CLI project to allow users to search for projects by typing partial or approximate names. The algorithm should be lightweight and should not rely on external crates, with the goal of better understanding the fuzzy matching process.

## Tasks

- [x] Implement the Levenshtein distance algorithm.
- [x] Add a scoring system to rank matches based on the computed distance.
- [x] Implement prefix matching to optimize performance when the input matches the beginning of a project name.
- [x] Create a function that returns the list of projects most relevant to the given input.
- [x] Test the algorithm on a project list to verify it works as expected.
